### ISSUE TITLE
Wrong dependencies

### ISSUE THREAD

**Issue by tainmar** [martinvigo/email2phonenumber#1]
Hi, I think you should install BeautifulSoup4 instead of BeautifulSoup.
`pip install BeautifulSoup4 requests` should therefore be specified in the docs.

**Comment by NTgitdude23** [comment]
Even installing BeautifulSoup4, im still getting the error of the package soupsieve not being installed yet i have manually installed it. ??

**Comment by tonynotears** [comment]
> Even installing BeautifulSoup4, im still getting the error of the package soupsieve not being installed yet i have manually installed it. ??

use python3 and try?

**Comment by martinvigo** [comment]
@tainmar thanks for reporting the issue. I just fixed the README. Also note that the script was developed for Python 2.x
