### ISSUE TITLE
Print....Line 526..

### ISSUE THREAD

**Issue by tonynotears** [martinvigo/email2phonenumber#2]
Hi, thanks for sharing this with us....

I think I see none of the "print" using "()", which prompts errors on our end,

Also, after adding all parentheses ..still seeing the line 532 error...
else:

SyntaxError: invalid Syntax

Using python 3.6, 3.7, running into same errors.

Not sure what your logic is, but I bet the nested if is the problem...

Thanks again

**Comment by martinvigo** [comment]
@tonynotears this script was developed for Python 2.x which print statements don't use brackets. You should run the script on Python 2.7

**Comment by martinvigo** [comment]
There is a pending pull request that will add Python 3 support thanks to @juanvelascogomez

**Comment by martinvigo** [comment]
I just merged @juanvelascogomez code which adds Python3 support
