### ISSUE TITLE
disable_warnings?

### ISSUE THREAD

**Issue by allelive** [martinvigo/email2phonenumber#27]
mi ritrovo con questo problema ma non o capito il problema e nenche come posso risolverlo grazie.

Traceback (ultima chiamata più recente):
File "email2phonenumber.py", riga 20, in request.packages.urllib3.disable_warnings
()
AttributeError: il modulo 'requests.packages.urllib3' non ha attributo "disable_warnings"

**Comment by martinvigo** [comment]
My italian is not great but you must install the dependencies
