### ISSUE TITLE
Make the identifying more accurate 

### ISSUE THREAD

**Issue by minanagehsalalma** [martinvigo/email2phonenumber#3]
Here what i think ... the most of the people have two social media accounts or more 
Example it will mostly  be fb and ig 
While fb provides to reset using phone or email  ..  ig just sents a link to email without showing any options it show up the reset link has been sent to T******@test.com
For 5 sec maybe ..  we just now have the last two numbers from fb and nothing else. 

So i don't  know why but i think services like truecaller would make the brute forcing somewhat easier  . .

**Comment by martinvigo** [comment]
@minanagehsalalma I am not sure I understand exactly what the request for the tool is? Can you clarify?

**Comment by minanagehsalalma** [comment]
> @minanagehsalalma I am not sure I understand exactly what the request for the tool is? Can you clarify?

I mean reverse search/bruteforce the numbers using caller identifying apps like truecaller   .. as ifthe target have only two social media accounts  would still  be very  to get their full numbers .

**Comment by martinvigo** [comment]
I see. The purpose of this tool is more oriented as an additional resource when your target does not have their data exposed in datafamrs like truecaller, pipl.com, etc. That is why it leverages NANPA data. It would definitely be beneficial to support those sites but I think it is beyond the scope of this tool. Thanks for the suggestion though!

**Comment by minanagehsalalma** [comment]
> I see. The purpose of this tool is more oriented as an additional resource when your target does not have their data exposed in datafamrs like truecaller, pipl.com, etc. That is why it leverages NANPA data. It would definitely be beneficial to support those sites but I think it is beyond the scope of this tool. Thanks for the suggestion though!

You are welcome  :)
